name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/**'
  pull_request:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Determine Docker tags
        id: tag
        run: echo ::set-output name=TAG::$(if [[ "${{ github.ref }}" == "refs/tags/v*.*.*" ]]; then echo "latest"; else echo "${{ github.ref }}" | sed -e "s/refs\/heads\///g"; fi)

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            woiza/telegram-bot-radarr:${{ steps.tag.outputs.TAG }}
          labels: ${{ steps.tag.outputs.labels }}