name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - 'develop'
    tags:
      - 'v*.*.*'
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'screenshots/**'
      - '.github/**'
      - .gitignore 
  pull_request:
    branches:
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: | 
            woiza/telegram-bot-radarr
            ghcr.io/woiza/telegram-bot-radarr

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to Docker Hub and GitHub Container Registry
        run: |
          docker buildx build --platform linux/amd64,linux/arm/v7,linux/arm64 -t woiza/telegram-bot-radarr:${{ steps.meta.outputs.tags }} .
          docker push woiza/telegram-bot-radarr:${{ steps.meta.outputs.tags }}
          docker tag woiza/telegram-bot-radarr:${{ steps.meta.outputs.tags }} ghcr.io/woiza/telegram-bot-radarr:${{ steps.meta.outputs.tags }}
          docker push ghcr.io/woiza/telegram-bot-radarr:${{ steps.meta.outputs.tags }}
